In [3]:
import numpy as np

In [35]:
M = np.array([[4, -5, 6],
              [7, -8, 6],
              [1.5, -.5, -2]])

M = np.array([[1.5, -1], [-.5, .5]])

In [36]:
M

array([[ 1.5, -1. ],
       [-0.5,  0.5]])

In [37]:
vals, vecs = np.linalg.eig(M)

In [38]:
print(vals)
print("")
print(vecs)

[1.8660254 0.1339746]

[[ 0.9390708   0.59069049]
 [-0.34372377  0.80689822]]


In [40]:
print(1 + (np.sqrt(3))/2)
print(1 - (np.sqrt(3))/2)

1.8660254037844386
0.1339745962155614


In [54]:
print(vecs[:, 1] * 1/0.80689822)
print(vecs[:, 0] * 1/-0.34372377)


[0.73205081 1.        ]
[-2.7320508  1.       ]


In [55]:
np.array([[-1 - np.sqrt(3), -1 + np.sqrt(3)],
          [1, 1]])

array([[-2.73205081,  0.73205081],
       [ 1.        ,  1.        ]])